quarkus.application.name=api-gateway

quarkus.rest-client.mcsv-pedidos.url=http://localhost:8082
quarkus.rest-client.mcsv-inventario.url=http://localhost:8081

quarkus.smallrye-openapi.info-title=API Gateway
quarkus.smallrye-openapi.info-version=1.0.0

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
