quarkus.application.name=mcsv-inventario

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=inventario
quarkus.datasource.password=inventario
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/inventario

quarkus.hibernate-orm.database.generation=validate

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

quarkus.smallrye-openapi.info-title=MCSV Inventario
quarkus.smallrye-openapi.info-version=1.0.0

kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.pedido-creado-in.connector=smallrye-kafka
mp.messaging.incoming.pedido-creado-in.topic=pedido-creado
mp.messaging.incoming.pedido-creado-in.group.id=mcsv-inventario
mp.messaging.incoming.pedido-creado-in.auto.offset.reset=earliest
mp.messaging.incoming.pedido-creado-in.value.deserializer=com.reto.inventario.messaging.PedidoCreadoEventDeserializer

mp.messaging.outgoing.stock-actualizado-out.connector=smallrye-kafka
mp.messaging.outgoing.stock-actualizado-out.topic=stock-actualizado
mp.messaging.outgoing.stock-actualizado-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.pedido-rechazado-out.connector=smallrye-kafka
mp.messaging.outgoing.pedido-rechazado-out.topic=pedido-rechazado
mp.messaging.outgoing.pedido-rechazado-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/inventario
