quarkus.application.name=mcsv-pedidos

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=pedidos
quarkus.datasource.password=pedidos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/pedidos

quarkus.hibernate-orm.database.generation=validate

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

quarkus.smallrye-openapi.info-title=MCSV Pedidos
quarkus.smallrye-openapi.info-version=1.0.0

kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.pedido-creado-out.connector=smallrye-kafka
mp.messaging.outgoing.pedido-creado-out.topic=pedido-creado
mp.messaging.outgoing.pedido-creado-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.stock-actualizado-in.connector=smallrye-kafka
mp.messaging.incoming.stock-actualizado-in.topic=stock-actualizado
mp.messaging.incoming.stock-actualizado-in.group.id=mcsv-pedidos
mp.messaging.incoming.stock-actualizado-in.auto.offset.reset=earliest
mp.messaging.incoming.stock-actualizado-in.value.deserializer=com.reto.pedidos.messaging.StockActualizadoEventDeserializer

mp.messaging.incoming.pedido-rechazado-in.connector=smallrye-kafka
mp.messaging.incoming.pedido-rechazado-in.topic=pedido-rechazado
mp.messaging.incoming.pedido-rechazado-in.group.id=mcsv-pedidos
mp.messaging.incoming.pedido-rechazado-in.auto.offset.reset=earliest
mp.messaging.incoming.pedido-rechazado-in.value.deserializer=com.reto.pedidos.messaging.PedidoRechazadoEventDeserializer

%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/pedidos
